### ISSUE TITLE
Jogadores com nomes iguais

### ISSUE THREAD

**Issue by SalehKhalil** [rafaela-queiroz/tic-tac-toe#2]
Olá, boa tarde!

Primeiramente, parabéns pelo projeto! Achei no feed no linkedin e testei por curiosidade. Acabei achando um probleminha quando temos jogadores com nomes iguais. Tem um switch case no componente Scoreboard que esta atribuindo os pontos sempre ao primeiro jogador devido ao nome dar true no primeiro case.

Segue as evidências:

<img width="450" alt="Captura de Tela 2021-05-14 às 12 29 32" src="https://user-images.githubusercontent.com/40570205/118294529-310bcc80-b4b1-11eb-9a8f-aeb617eccd6f.png">
<img width="450" alt="Captura de Tela 2021-05-14 às 12 29 44" src="https://user-images.githubusercontent.com/40570205/118294562-39640780-b4b1-11eb-9d29-d0d4949158e0.png">

Acredito que o que poderia solucionar esse problema, seria você sempre verificar se quem ganhou foi a circulo ou o xis e usar apenas os nomes dos jogadores na view, sem estar na suas regras.

Boa sorte!

**Comment by rafaela-queiroz** [comment]
Show @SalehKhalil , não tinha pensado nesse cenário. Muito obrigada pela sugestão, irei desenvolver a solução e em breve volto com novidades 😁

**Comment by rafaela-queiroz** [comment]
Corrigido e já em produção @SalehKhalil . Obrigada pela contribuição 🎉

**Comment by SalehKhalil** [comment]
Muito bom @rafaela-queiroz, conferi e esta show!

Parabéns pelo empenho!!
